helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: my-prometheus
  namespace: opencost
  valuesInline:
    pushgateway:
      enabled: false
    alertmanager:
      enabled: false
  valuesFile: https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/prometheus/extraScrapeConfigs.yaml
generatorOptions:
 disableNameSuffixHash: true
namespace: opencost
resources:
- https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml
- ui-service.yml
patchesStrategicMerge:
  - ValueOverrides.yml
configMapGenerator:
  - name: opencost-config
    literals:
    - PROMETHEUS_SERVER_ENDPOINT=http://my-prometheus-server.svc
    - CLOUD_PROVIDER_API_KEY=AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U # The GCP Pricing API requires a key. This is supplied just for evaluation.
    - CLUSTER_ID=cluster-one # the default cluster id.
  - name: opencost-ui-config
    literals:
    - BASE_URL=http://localhost:9090/allocation #Override this to the URL at which a client computer viewing the UI can access ther opencost cost model, which is served my a different container in this pod on port 9003. This will not work until this PR merges: https://github.com/opencost/opencost/pull/1417
          
