apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
spec:
  template:
    spec:
      containers:
      - name: opencost
        env: []
        envFrom:
        - configMapRef:
            name: opencost-config   
        readinessProbe:
          tcpSocket:
            port: 9003
          initialDelaySeconds: 5
          periodSeconds: 10   
        ports:
        - containerPort: 9003
      - name: ui
        image: timbru31/node-alpine-git:latest
        command: ["/bin/sh","-c","git clone https://github.com/opencost/opencost.git && cd opencost/ui && ls && npm install; npx parcel src/index.html"]
        #command: ["/bin/sh","-c","git clone https://github.com/stephenatwell/opencost-uiconfigurability.git && cd opencost-uiconfigurability/ui && ls && npm install; npx parcel src/index.html"] # note, this git repo has the fix to allow changing url.... but is not being actively maintained.        
        ports:
        - containerPort: 1234
        readinessProbe:
          tcpSocket:
            port: 1234
          initialDelaySeconds: 5
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: opencost-ui-config 
          
