
apiVersion: v1
kind: Service
metadata:
  name: my-prometheus-server
  namespace: opencost
spec:
  type: LoadBalancer #ClusterIP # change to loadbalancer to make accessible outside the cluster.
  

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-prometheus-server
  namespace: opencost
spec:
  accessModes:
  - ReadWriteMany # cannot mount a readwriteOnce volume when doing a canary deployment strategy. need to with use ReadWriteMany, or switch to the prometheus operator.
---
#Replace the persistent volume claim with an empty dir for clusters that are not setup for ReadWriteMany
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-prometheus-server
  namespace: opencost
spec:
  template:
    spec:
      volumes:
      - name: storage-volume
        emptyDir: {} 
        persistentVolumeClaim:
          $patch: delete

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
spec:
  template:
    spec:
      containers:
      - name: opencost
        env: []
        envFrom:
        - configMapRef:
            name: opencost-config   
        readinessProbe:
          tcpSocket:
            port: 9003
          initialDelaySeconds: 5
          periodSeconds: 10   
        ports:
        - containerPort: 9003
      - name: ui
        image: timbru31/node-alpine-git:latest
        command: ["/bin/sh","-c","git clone https://github.com/opencost/opencost.git && cd opencost/ui && ls && npm install; npx parcel src/index.html"]
        ports:
        - containerPort: 1234
        readinessProbe:
          tcpSocket:
            port: 1234
          initialDelaySeconds: 5
          periodSeconds: 10 
          