---
generatorOptions:
 disableNameSuffixHash: true
namespace: opencost
resources:
- https://raw.githubusercontent.com/opencost/opencost/develop/kubernetes/opencost.yaml
patchesStrategicMerge:
  - ValueOverrides.yml
configMapGenerator:
  - name: opencost-config
    literals:
    - PROMETHEUS_SERVER_ENDPOINT=http://my-prometheus-server.prometheus.svc
    - CLOUD_PROVIDER_API_KEY=AIzaSyD29bGxmHAVEOBYtgd8sYM2gM2ekfxQX4U # The GCP Pricing API requires a key. This is supplied just for evaluation.
    - CLUSTER_ID=cluster-one # the default cluster id.
